import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex min-h-screen items-center text-dark dark:text-light sm:items-start">
        <Layout className="z-0 inline-block h-full w-full bg-light p-32 dark:bg-dark xl:p-24 lg:p-16 
      md:p-12 sm:p-8 !pt-0 md:!pt-16 sm:!pt-16">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 lg:hidden md:inline-block md:w-full">
              <Image
                className="h-auto w-full"
                src={profilePic}
                alt="myImage"
                priority
                sizes="
                  (max-width: 768px) 100vw,
                  (max-width: 1200px) 50vw,
                  50vw
                "
              />
            </div>
            <div className="w-1/2 flex flex-col self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="py-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start gap-4 mt-2 lg:self-center">
                <Link
                  href="/Yeasin_Arafat_FE_Dev_4Yeasr.pdf"
                  className="bg-dark text-light text-lg font-semibold flex items-center gap-1 py-2.5 px-6 rounded-lg border border-solid border-transparent transition-all hover:bg-light hover:text-dark hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  target="_blank"
                  download={true}
                >
                  Resume
                  <LinkArrow className={"h-auto !w-6 md:!w-4"} />
                </Link>
                <Link
                  href="mailto:ayeasin108@gmail.com"
                  className="text-dark text-lg font-medium capitalize underline dark:text-light md:text-base"
                  target="_blank"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image className="w-full h-auto" src={lightBulb} alt="light-bulb" />
        </div>
      </main>
    </>
  );
}
