import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image className="w-full h-auto" src={profilePic} alt="myImage" />
            </div>
            <div className="w-1/2 flex flex-col self-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl text-left"
              />
              <p className="py-4 text-base font-medium">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start gap-4 mt-2">
                <Link
                  href="/Yeasin_Arafat_FE_Dev_4Yeasr.pdf"
                  className="bg-dark text-light text-lg font-semibold flex items-center gap-2 py-2.5 px-6 rounded-lg border border-solid border-transparent transition-all hover:bg-light hover:text-dark hover:border-dark"
                  target="_blank"
                  download={true}
                >
                  Resume
                  <LinkArrow className={'w-6'} />
                </Link>
                <Link href="mailto:ayeasin108@gmail.com" className="text-dark text-lg font-medium capitalize underline" target="_blank">
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image className="w-full h-auto" src={lightBulb} alt="light-bulb" />
        </div>
      </main>
    </>
  );
}
